name: Deploy to Pronamic WordPress directory

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy to Pronamic WordPress directory'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: Pronamic WordPress directory
      url: https://wp.pronamic.directory/plugins/pronamic-pay-with-mollie-for-gravity-forms/

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Download'
        run: |
          gh release download v${{ inputs.version }} --repo ${{ github.repository }} --pattern pronamic-pay-with-mollie-for-gravity-forms.${{ inputs.version }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'pronamic-downloads'
          workload_identity_provider: 'projects/623467151959/locations/global/workloadIdentityPools/github/providers/my-repo'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'
