name: Deploy to Pronamic WordPress directory

on:
  workflow_dispatch:
    inputs:
      latest:
        default: true
        type: boolean
        description: 'Deploy as "Latest"'
      tag:
        description: 'Tag to deploy to Pronamic WordPress directory'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: Pronamic WordPress directory
      url: https://wp.pronamic.directory/plugins/pronamic-pay-with-mollie-for-gravity-forms/

    permissions:
      id-token: 'write'

    steps:
      - name: Deploy
        uses: pronamic/action-wp-pronamic-directory-plugin-deploy@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          username: pronamic
          password: ${{ secrets.WP_PRONAMIC_DIRECTORY_PASSWORD }}
          slug: pronamic-pay-with-mollie-for-gravity-forms
          tag: ${{ inputs.tag }}
          latest: ${{ inputs.latest }}
